server.port=8082
spring.application.name=inventory-microservice
kafka.orders.topic=orders.created
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-created-events
spring.kafka.consumer.consumer.properties.spring.json.truested.packages=*
